require 'virtus'
require 'cups'
require_relative 'printing/collection'
require_relative 'printing/available'
require_relative 'printing/json_model'
require_relative 'printing/job'
require_relative 'printing/printer'
require_relative 'printing/api'
